# Generated by Django 5.1.2 on 2024-10-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcount',
            name='meal_type',
            field=models.CharField(default='Breakfast', max_length=10),
        ),
        migrations.AddField(
            model_name='mealcount',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealcount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
