# Generated by Django 5.1.2 on 2024-10-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_permissionrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='date_submitted',
            new_name='date_reported',
        ),
    ]
